name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 src/ --max-line-length=120 || true

    - name: Smoke test imports
      run: |
        python - <<'PY'
        import torch, transformers, datasets, peft, bitsandbytes
        print("Torch:", torch.__version__)
        print("Transformers:", transformers.__version__)
        print("Datasets:", datasets.__version__)
        print("PEFT:", peft.__version__)
        PY

    - name: Hugging Face login
      run: |
        mkdir -p ~/.huggingface
        echo -n "${{ secrets.HF_TOKEN }}" > ~/.huggingface/token
        
    - name: Run mini prompt test (CPU)
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python src/prompt_eval.py           --config configs/config.yaml           --k_shot 0           --seed 41           --max_eval 2           --out results/test_prompt.json
        cat results/test_prompt.json

